name: flutter_pos_printer_platform
description: A flutter plugin that prints esc commands to printers in different platforms such as android, ios, windows and different interfaces Bluetooth and BLE, TCP and USB
version: 1.3.0
homepage: https://github.com/arthas1888/flutter_pos_printer_platform

environment:
  sdk: '>=2.18.4 <3.3.10'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  # flutter_star_prnt: ^2.3.6
  enum_to_string: ^2.0.1
  image: ^4.0.15

  network_info_plus: ^3.0.2
  ping_discover_network_forked: ^0.0.1
  rxdart: ^0.27.7
  gbk_codec: ^0.4.0
  hex: ^0.2.0
  dart_ping: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.sersoluciones.flutter_pos_printer_platform
        pluginClass: FlutterPosPrinterPlatformPlugin
      ios:
        pluginClass: FlutterPosPrinterPlatformPlugin
      windows:
        pluginClass: FlutterPosPrinterPlatformPlugin

  assets:
    - assets/resources/capabilities.json
    - packages/flutter_pos_printer_platform/resources/capabilities.json
    
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
